jekyll-asciidoc.gemspec

This will enable the gem to be installed from Rubygems via `gem install jekyll-asciidoc` (per the instructions in the README) without having to specify the `--pre` flag. Since we are releasing this as a gem for production use, seems that v.1.0.0 is appropriate. WDYT? Once this is done I will re-publish the gem to Rubygems.

Set version to 1.0.0 (remove prerelease text)

---

.gitignore
README.adoc

I propose some changes to make cleaner separation of plugin management and site building when using `Bundler`

Documentation improvements - Bundler, front matter

---

jekyll-asciidoc.gemspec

Bundler complains when running `bundle exec rake` without rake in gemspec/Gemfile.

Add rake dependency to gemspec

---

lib/jekyll-asciidoc.rb

This fixes two warnings I'm seeing with Jekyll 3.
Deprecation: Collection#each should be called on the #docs array directly.
Called by ./_plugins/jekyll-asciidoc.rb:119:in `generate'.
Deprecation: Document#ext is now a key in the #data hash.
Called by ./_plugins/jekyll-asciidoc.rb:120:in `block in generate'.

jekyll-asiidoc.rb: Mitigating some warnings for use with Jekyll 3 use.

---

lib/jekyll-asciidoc.rb

* use env=site and env-site instead of env-jekyll
* introduce site-gen=jekyll and site-gen-jekyll
* define jekyll-version attribute

resolves #55 align environment-related attributes with other site generators

---

README.adoc
lib/jekyll-asciidoc.rb

- disable Liquid preprocessor on AsciiDoc files by default
- allow Liquid preprocessor to be enabled by setting the liquid page variable

resolves #65 disable Liquid preprocessor on AsciiDoc files by default

---

README.adoc
jekyll-asciidoc.gemspec

- document minimum version of Jekyll as 2.0.0
- make jekyll gem a runtime dependency (so we can enforce minimum version)
- remove version of rake gem

resolves #76 document minimum version of Jekyll

---

README.adoc
lib/jekyll-asciidoc.rb

- disable hard line breaks by default (i.e., `hardbreaks` attribute)
- document how to reeanble

resolves #69 disable hard line breaks by default

---

README.adoc
lib/jekyll-asciidoc.rb

- move AsciiDoc configuration to Hash under asciidoc key 
- use old keys if new keys aren't specified
- add deprecation warning if old structure is detected
- chomp trailing hyphen on page_attribute_prefix in initialize
- treat nil value for page_attribute_prefix as empty string
- use a module to mark initialized configuration
- update README to document new keys

resolves #82 restructure configuration keys

---

lib/jekyll-asciidoc.rb

- use Jekyll.logger to emit messages
- use Jekyll.logger to abort
- make messages more consistent
- minor updates to source style and formatting

resolves #85 use Jekyll.logger to emit messages

---

README.adoc
lib/jekyll-asciidoc.rb
lib/jekyll-asciidoc/version.rb
spec/fixtures/require_front_matter_header/_config.yml
spec/fixtures/require_front_matter_header/_layouts/default.html
spec/fixtures/require_front_matter_header/with-front-matter-header.adoc
spec/fixtures/require_front_matter_header/without-front-matter-header.adoc
spec/jekyll-asciidoc_spec.rb

- store reference to original method
- restore original method if require_front_matter_header is true
- always delegate to original method (not previously curried method)
- add tests to ensure require_front_matter_header config option is enforced

redefine has_yaml_header? method properly

---

README.adoc

- document how to setup GitLab Pages to build and deploy a Jekyll site
- update and reorganize documentation on GitHub Pages
- tuck conums behind line comment in source listings on GitHub

resolves #47 document how to use plugin with GitLab Pages

---

lib/jekyll-asciidoc/converter.rb
lib/jekyll-asciidoc/integrator.rb
spec/jekyll-asciidoc_spec.rb

- only register callbacks for pre_render and post_render hooks once
- register callbacks as static methods so they work on any site instance
- add test to ensure hook callbacks are only registered once

only register hooks once

---

lib/jekyll-asciidoc/integrator.rb
spec/fixtures/explicit_site_time/_config.yml
spec/fixtures/explicit_site_time/_layouts/default.html
spec/fixtures/explicit_site_time/home.adoc
spec/jekyll-asciidoc_spec.rb

- align localtime and localdate AsciiDoc attributes with site.time and site.timezone
- add test to verify localdatetime matches site.time
- document conditions under which generate method is invoked

resolves #117 align localtime and localdate attributes with site.time

---

CHANGELOG.adoc
README.adoc
lib/jekyll-asciidoc/converter.rb
lib/jekyll-asciidoc/filters.rb
lib/jekyll-asciidoc/mixins.rb
spec/fixtures/tocify_filter/_config.yml
spec/fixtures/tocify_filter/_layouts/default.html
spec/fixtures/tocify_filter/index.adoc
spec/jekyll-asciidoc_spec.rb

- promote current document to page variable named document
- add to_liquid method to ::Asciidoctor::Document
- add tocify_asciidoc filter to generate toc from ::Asciidoctor::Document instance
- add test for tocify_asciidoc filter
- document tocify_asciidoc filter in README
NOTE: This Liquid filter is only available when using Jekyll 3 or better.

resolves #37 add liquid filter to generate toc

---

CHANGELOG.adoc
README.adoc
lib/jekyll-asciidoc/integrator.rb
spec/fixtures/with_posts/_layouts/post.html
spec/fixtures/with_posts/_posts/2016-06-15-post-with-date.adoc
spec/fixtures/with_posts/_posts/2016-07-15-post-with-date-and-tz.adoc
spec/fixtures/with_posts/_posts/2016-07-20-post-with-date-in-revision-line.adoc
spec/jekyll-asciidoc_spec.rb

- parse value of revdate attribute in posts using Jekyll::Utils.parse_date
- add tests to verify revdate is parsed correctly and assigned as date of post
- document how to specify time part for post date

parse revdate using Jekyll::Utils.parse_date

---

CHANGELOG.adoc
lib/jekyll-asciidoc/converter.rb
spec/fixtures/with_posts/_config.yml

- auto-extracted excerpt is parsed by converter, but hooks aren't triggered
- clear :docdir value of base_dir if paths not available

clear residual :docdir value of base_dir option before conversion

---

lib/jekyll-asciidoc/compat.rb
lib/jekyll-asciidoc/converter.rb

- use correct page payload for the version of Jekyll in use

fix tocify filter

---

lib/jekyll-asciidoc/converter.rb
spec/fixtures/basic_site/with-front-matter-header-only.adoc
spec/jekyll-asciidoc_spec.rb

- use fallback when document only has a front matter header
- add test

resolves #179 handle case when document body is empty

---

README.adoc

Small documentation issue. Travis does deployments for GitHub, not gitlab.

Small doc typo - Travis deploys to GitHub

---

README.adoc

According to Dan's proposal, a note has been added to README.adoc
so that the user knows why his variables from the document header may not be visible.

Add a hint in README for right plugin order

---

README.adoc

I discovered a way to be able to conditionally disable a table of contents from showing on certain pages by using a custom attribute and an `if` statement in my template. Since I struggled with it for a bit before figuring it out, I thought it might be helpful in the official documentation.
(It seems my editing client stripped a couple of hanging spaces at the ends of lines, hope those are OK...).

Add tip to conditionally disable TOC via Liquid template

---

README.adoc

Looks like you've got an issue with nested quotes in the example of linking to a pygments generated stylesheet?

Fix nested quotes in pygments stylesheet reference

---

.travis.yml
CHANGELOG.adoc
appveyor.yml
jekyll-asciidoc.gemspec
spec/fixtures/include_relative_to_root/_config.yml
spec/spec_helper.rb

moved the `include_relative_to_root` fixture _config.yml to the expected location at root.
Added a check that there is a _config.yml at root of each fixture.

resolves #239 broken tests

---

docs/modules/ROOT/pages/installation.adoc

We're now only able to test ruby 2.4.x, but when 3.0 was released apparently testing on 2.3.0 also worked, so document that.

Restore earliest ruby version for released 3.0 to 2.3.0

---

README.adoc

We need to keep the old README in place until the new docs are live.
This reverts commit 59dad77f2b78eb46b31accc2ec72774f9cfd5f6e.

Revert "truncate README.adoc"

---

CHANGELOG.adoc
docs/modules/ROOT/pages/liquid-filters.adoc
lib/jekyll-asciidoc/filters.rb
spec/fixtures/docinfo_filter/_config.yml
spec/fixtures/docinfo_filter/_layouts/default.html
spec/fixtures/docinfo_filter/docinfo-custom.html
spec/fixtures/docinfo_filter/docinfo-footer.html
spec/fixtures/docinfo_filter/docinfo-header.html
spec/fixtures/docinfo_filter/docinfo.html
spec/fixtures/docinfo_filter/index.adoc
spec/jekyll-asciidoc_spec.rb
tasks/rspec.rake

This introduces a liquid filter that inserts docinfo from the Asciidoctor docinfo mechanism.  Not only the standard head, header, and footer locations are supported, but also any custom location. See the included documentation for details.

resolves #164: implement docinfo support

---

jekyll-asciidoc.gemspec
lib/jekyll-asciidoc/converter.rb
lib/jekyll-asciidoc/excerpt.rb
spec/fixtures/posts_with_excerpts/_config.yml
spec/fixtures/posts_with_excerpts/plain/_config.yml
spec/fixtures/posts_with_excerpts/with_plugin/_config.yml
spec/jekyll-asciidoc_spec.rb
spec/spec_helper.rb

and register a before_render hook for it.
All tests pass with this, with one of the problematic additional plugins registered (jekyll-mentions) for the excerpt tests.
Is there anything else to look out for? Other events/hooks?
Is unconditionally adding the additional plugin for the excerpt tests reasonable?

resolves #230: claim an excerpt is an excerpt,

---

docs/modules/ROOT/pages/global-page-attributes.adoc
docs/modules/ROOT/pages/page-attributes.adoc

This documents existing behavior.

Document yaml escaping and continuations for attributes (#158) [skip ci]

---

.github/workflows/ci.yml
README.adoc
docs/modules/ROOT/pages/supplemental-assets.adoc
jekyll-asciidoc.gemspec

Old pygments.rb 1.x only works with Python 2 that is EOL.
It also doesn't work on JRuby + Windows.

Use modern pygments.rb
